import type { WishData } from '../templates/types';

export const templateMockData: Record<WishData['templateType'], WishData> = {
  'birthday-universe': {
    templateType: 'birthday-universe',
    title: "Happy Birthday!",
    targetName: "Navya",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a beautiful day filled with love, laughter, and endless joy! You deserve all the happiness in the world. Tap the cover to reveal your surprise!",
    primaryColor: "#ffb6c1",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Classic Happy Birthday",
    extraMessage: "I wanted to make this space just to tell you everything I feel. Every single day with you feels like a gift. From the quiet mornings to our late-night laughs, you bring a light into my life that I never knew existed.",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",

    // Quiz defaults
    quizQ1: "What is my favorite color?",
    quizA1a: "Pink 💗",
    quizA1b: "Blue 💙",
    quizA1c: "Purple 💜",
    quizA1d: "Red ❤️",
    quizA1correct: 0,

    quizQ2: "What is my dream travel destination?",
    quizA2a: "Paris 🗼",
    quizA2b: "Maldives 🏝️",
    quizA2c: "Tokyo 🗾",
    quizA2d: "Switzerland 🏔️",
    quizA2correct: 1,

    quizQ3: "What makes me happiest?",
    quizA3a: "Good food 🍕",
    quizA3b: "Sunsets 🌅",
    quizA3c: "Being with you 🥰",
    quizA3d: "Music 🎵",
    quizA3correct: 2,

    // Photo gallery defaults (Unsplash birthday-themed)
    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  },
  'happy-birthday-classic': {
    templateType: 'happy-birthday-classic',
    title: "Happy Birthday!",
    targetName: "Navya",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a beautiful day filled with love, laughter, and endless joy! You deserve all the happiness in the world. Tap the cover to reveal your surprise!",
    primaryColor: "#ffd700",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Classic Happy Birthday",
    extraMessage: "I wanted to make this space just to tell you everything I feel. Every single day with you feels like a gift. From the quiet mornings to our late-night laughs, you bring a light into my life that I never knew existed.",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",

    // Quiz defaults
    quizQ1: "What is my favorite color?",
    quizA1a: "Pink 💗",
    quizA1b: "Blue 💙",
    quizA1c: "Purple 💜",
    quizA1d: "Red ❤️",
    quizA1correct: 0,

    quizQ2: "What is my dream travel destination?",
    quizA2a: "Paris 🗼",
    quizA2b: "Maldives 🏝️",
    quizA2c: "Tokyo 🗾",
    quizA2d: "Switzerland 🏔️",
    quizA2correct: 1,

    quizQ3: "What makes me happiest?",
    quizA3a: "Good food 🍕",
    quizA3b: "Sunsets 🌅",
    quizA3c: "Being with you 🥰",
    quizA3d: "Music 🎵",
    quizA3correct: 2,

    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  },
  'pop-up-storybook': {
    templateType: 'pop-up-storybook',
    title: "Your Fairytale Chapter!",
    targetName: "Navya",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a beautiful day filled with love, laughter, and endless joy! You deserve all the happiness in the world. Tap the cover to reveal your surprise!",
    primaryColor: "#8b5cf6",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Classic Happy Birthday",
    extraMessage: "I wanted to make this space just to tell you everything I feel. Every single day with you feels like a gift. From the quiet mornings to our late-night laughs, you bring a light into my life that I never knew existed.",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
    quizQ1: "What is my favorite color?", quizA1a: "Pink 💗", quizA1b: "Blue 💙", quizA1c: "Purple 💜", quizA1d: "Red ❤️", quizA1correct: 0,
    quizQ2: "What is my dream travel destination?", quizA2a: "Paris 🗼", quizA2b: "Maldives 🏝️", quizA2c: "Tokyo 🗾", quizA2d: "Switzerland 🏔️", quizA2correct: 1,
    quizQ3: "What makes me happiest?", quizA3a: "Good food 🍕", quizA3b: "Sunsets 🌅", quizA3c: "Being with you 🥰", quizA3d: "Music 🎵", quizA3correct: 2,
    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  },
  'romantic-anime-birthday': {
    templateType: 'romantic-anime-birthday',
    title: "Happy Birthday My Love!",
    targetName: "Navya",
    senderName: "Arjun",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a beautiful day filled with love, laughter, and endless joy! You deserve all the happiness in the world. Tap the cover to reveal your surprise!",
    primaryColor: "#f8c8d8",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Classic Happy Birthday",
    extraMessage: "Since our first conversation, you’ve been the calm spark that changed my world. Every day feels warmer because you exist.",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1518199266791-5375a83164ba?auto=format&fit=crop&w=800&q=80",
    quizQ1: "What is my favorite color?", quizA1a: "Pink 💗", quizA1b: "Blue 💙", quizA1c: "Purple 💜", quizA1d: "Red ❤️", quizA1correct: 0,
    quizQ2: "What is my dream travel destination?", quizA2a: "Paris 🗼", quizA2b: "Maldives 🏝️", quizA2c: "Tokyo 🗾", quizA2d: "Switzerland 🏔️", quizA2correct: 1,
    quizQ3: "What makes me happiest?", quizA3a: "Good food 🍕", quizA3b: "Sunsets 🌅", quizA3c: "Being with you 🥰", quizA3d: "Music 🎵", quizA3correct: 2,
    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  },
  'cinematic-3d-birthday': {
    templateType: 'cinematic-3d-birthday',
    title: "Happy Birthday Navya ❤️",
    targetName: "Navya",
    senderName: "Arjun",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "You are the most beautiful chapter my life ever received. Every smile of yours feels like magic, every moment with you feels unforgettable. Today is not just your birthday — it’s the celebration of the person who makes my world brighter every single day.",
    primaryColor: "#ff3366",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Cinematic Birthday Theme",
    extraMessage: "Forever Yours ❤️",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    quizQ1: "What is my favorite color?", quizA1a: "Pink 💗", quizA1b: "Blue 💙", quizA1c: "Purple 💜", quizA1d: "Red ❤️", quizA1correct: 0,
    quizQ2: "What is my dream travel destination?", quizA2a: "Paris 🗼", quizA2b: "Maldives 🏝️", quizA2c: "Tokyo 🗾", quizA2d: "Switzerland 🏔️", quizA2correct: 1,
    quizQ3: "What makes me happiest?", quizA3a: "Good food 🍕", quizA3b: "Sunsets 🌅", quizA3c: "Being with you 🥰", quizA3d: "Music 🎵", quizA3correct: 2,
    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  },
  'birthday-original': {
    templateType: 'birthday-original',
    title: "Happy Birthday",
    targetName: "Anggie",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Today is...\nas beautiful as other days\nbut you realize\nanother year has gone\nin a blink of the eyes\nhowever\nDo you know..?\ntoday is just special\nso special to you\nthat's why\nLet's make it...\nthe best celebration ever\nand let me share...\na piece of happiness to you\nI made all this...\nas a birthday present to you\nI'm glad we met on zzz\nthanks for the friendship we made\nthanks for everything\nI wish you all the best\nMay your life be at ease\nMay all your wishes come true\nRemember\nyour ambitions\nyou live as a free bird...\nflying in the blue sky\nNow things are different...\nreal story of your life\nis just about to begin\nindeed..\nbut...\ndon't worry\nbecause...\nGod has your back\nand\nthis year will be better\nand I hope\nyou'll find...\nhappiness along the way\nkeep your spirit up\nenjoy every single moment...\nthat you experience today\nfill it with your most beautiful smile\nand make it the best memory..\nlastly...\nI'd like to wish you one more time\na very happy birthday babyy ❤️",
    primaryColor: "#FFDAB9",
    musicUrl: "/templates/birthday-original/audio/hbd.mp3",
    musicName: "Happy Birthday Original",
    extraMessage: "This birthday present is built just for you! ❤️",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "/templates/birthday-original/images/person.png",
    quizQ1: "What is my favorite color?", quizA1a: "Pink 💗", quizA1b: "Blue 💙", quizA1c: "Purple 💜", quizA1d: "Red ❤️", quizA1correct: 0,
    quizQ2: "What is my dream travel destination?", quizA2a: "Paris 🗼", quizA2b: "Maldives 🏝️", quizA2c: "Tokyo 🗾", quizA2d: "Switzerland 🏔️", quizA2correct: 1,
    quizQ3: "What makes me happiest?", quizA3a: "Good food 🍕", quizA3b: "Sunsets 🌅", quizA3c: "Being with you 🥰", quizA3d: "Music 🎵", quizA3correct: 2,
    photo1: "/templates/birthday-original/images/photo1.jpg",
    photo2: "/templates/birthday-original/images/photo2.jpg",
    photo3: "/templates/birthday-original/images/photo3.jpg",
    photo4: "/templates/birthday-original/images/photo4.jpg",
    photo5: "/templates/birthday-original/images/photo5.jpg",
    photo6: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=600&q=80"
  },
  'galactic-3d-heart': {
    templateType: 'galactic-3d-heart',
    title: "Happy Birthday Siri ❤️",
    targetName: "Siri",
    senderName: "Arjun",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a beautiful day filled with love, laughter, and endless joy! You deserve all the happiness in the world. Tap the cover to reveal your surprise!",
    primaryColor: "#d4af37",
    musicUrl: "https://raw.githubusercontent.com/ProgrammerGaurav/happy-birthday/master/Happy%20Birthday_files/music.mp3",
    musicName: "Royal Galactic Theme",
    extraMessage: "Forever Yours ❤️",
    rsvpEmail: "birthday@wisher.net",
    bgImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
    quizQ1: "What is my favorite color?", quizA1a: "Pink 💗", quizA1b: "Blue 💙", quizA1c: "Purple 💜", quizA1d: "Red ❤️", quizA1correct: 0,
    quizQ2: "What is my dream travel destination?", quizA2a: "Paris 🗼", quizA2b: "Maldives 🏝️", quizA2c: "Tokyo 🗾", quizA2d: "Switzerland 🏔️", quizA2correct: 1,
    quizQ3: "What makes me happiest?", quizA3a: "Good food 🍕", quizA3b: "Sunsets 🌅", quizA3c: "Being with you 🥰", quizA3d: "Music 🎵", quizA3correct: 2,
    photo1: "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=600&q=80",
    photo2: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    photo3: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=600&q=80",
    photo4: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80"
  }
};
