import type { WishData } from '../templates/types';

export const templateMockData: Record<WishData['templateType'], WishData> = {
  'retro-box': {
    templateType: 'retro-box',
    title: "Happy 25th Birthday!",
    targetName: "Alexander Mercer",
    date: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 16),
    message: "Wishing you a spectacular year ahead filled with joy, magic, and boundless success! You deserve the world. Click the box to open your surprise!",
    primaryColor: "#d30f0f",
    extraMessage: "P.S. Surprise rooftop drinks start at 8:00 PM!",
    rsvpEmail: "alex@wisher.net"
  },
  'neon-cyberpunk-vinyl': {
    templateType: 'neon-cyberpunk-vinyl',
    title: "Synthwave B-Day Vibe",
    targetName: "Cyber Unit 09",
    date: new Date(Date.now() + 86400000 * 5).toISOString().slice(0, 16),
    message: "System status: Joy maximized. Compilation of another year successful. Spin the vinyl to decrypt your core birthday sequence!",
    primaryColor: "#ff007f",
    extraMessage: "Coordinates locked. Arrival: Midnight.",
    rsvpEmail: "cyber@wisher.net"
  },
  'pop-up-storybook': {
    templateType: 'pop-up-storybook',
    title: "The Fairytale Chronicle",
    targetName: "Lady Penelope",
    date: new Date(Date.now() + 86400000 * 10).toISOString().slice(0, 16),
    message: "Once upon a time, a magical chapter began. Open this storybook to release balloon cascades, cardboard cake layers, and endless celebrations!",
    primaryColor: "#d4af37",
    extraMessage: "Grand banquet at the castle hall starts at dusk.",
    rsvpEmail: "penelope@wisher.net"
  },
  'cosmic-constellation': {
    templateType: 'cosmic-constellation',
    title: "Stellar Alignment",
    targetName: "Orion Star-Walker",
    date: new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 16),
    message: "Your birthday is written in the cosmos! Break the glass sphere to connect the stars and align your custom birthday constellation.",
    primaryColor: "#00ffff",
    extraMessage: "Observe the telescope viewing party in the observatory.",
    rsvpEmail: "orion@wisher.net"
  },
  'magical-balloon-release': {
    templateType: 'magical-balloon-release',
    title: "Wishes Set Free!",
    targetName: "Sophia Loren",
    date: new Date(Date.now() + 86400000 * 1).toISOString().slice(0, 16),
    message: "Your special birthday surprise is ready! Release the balloon knot to scatter the balloons and see your magical wishes.",
    primaryColor: "#d30f0f",
    extraMessage: "P.S. Join us in the garden for cake and champagne at 7:00 PM!",
    rsvpEmail: "sophia@wisher.net"
  },
  'elegant-card': {
    templateType: 'elegant-card',
    title: "Together in Love",
    targetName: "Sarah & David",
    date: new Date(Date.now() + 86400000 * 30).toISOString().slice(0, 16),
    message: "With hearts full of love, we invite you to share our joy as we flip the page to a new chapter and exchange our vows.",
    primaryColor: "#d4af37",
    extraMessage: "Garden reception to follow.",
    rsvpEmail: "sarahanddavid@wisher.net",
    brideName: "Sarah Jennings",
    groomName: "David Miller",
    weddingTime: "16:00",
    venueName: "The Grand Plaza, Crystal Ballroom",
    googleMapsUrl: "https://maps.google.com"
  },
  'wax-seal-scroll': {
    templateType: 'wax-seal-scroll',
    title: "The Royal Union Scroll",
    targetName: "Charlotte & James",
    date: new Date(Date.now() + 86400000 * 45).toISOString().slice(0, 16),
    message: "By royal decree, you are summoned to witness the grand union of Charlotte & James. Crack the stamped wax seal to unroll our linen scroll details.",
    primaryColor: "#b80c0c",
    extraMessage: "Grand ballroom waltz commences at sunset.",
    rsvpEmail: "royalwedding@wisher.net",
    brideName: "Charlotte Davis",
    groomName: "James Thompson",
    weddingTime: "18:00",
    venueName: "The Royal Majestic Hall",
    googleMapsUrl: "https://maps.google.com"
  },
  'infinity-origami-fold': {
    templateType: 'infinity-origami-fold',
    title: "The Origami Marriage",
    targetName: "Emma & Benjamin",
    date: new Date(Date.now() + 86400000 * 20).toISOString().slice(0, 16),
    message: "Love folds, unfolds, and expands infinitely. Unfold this origami invitation cards sequentially to uncover our countdown, venue, and map layers.",
    primaryColor: "#d30f0f",
    extraMessage: "Casual beach dinner and drinks. Dress code: Linen.",
    rsvpEmail: "emmaandben@wisher.net",
    brideName: "Emma Watson",
    groomName: "Benjamin Clark",
    weddingTime: "15:30",
    venueName: "Seaside Sunset Pavilion",
    googleMapsUrl: "https://maps.google.com"
  },
  'glass-botanical-box': {
    templateType: 'glass-botanical-box',
    title: "Botanical Terrarium Invite",
    targetName: "Grace & William",
    date: new Date(Date.now() + 86400000 * 60).toISOString().slice(0, 16),
    message: "Step inside our green sanctuary display case! Open the golden glass door to enter our botanical garden wedding details card.",
    primaryColor: "#2d6a4f",
    extraMessage: "Forest glade chapel ceremony.",
    rsvpEmail: "graceandwill@wisher.net",
    brideName: "Grace Sterling",
    groomName: "William Harrison",
    weddingTime: "17:00",
    venueName: "Green Sanctuary Conservatory",
    googleMapsUrl: "https://maps.google.com"
  },
  'modern-door': {
    templateType: 'modern-door',
    title: "Welcome to Our New Nest",
    targetName: "The Sharma Family",
    date: new Date(Date.now() + 86400000 * 14).toISOString().slice(0, 16),
    message: "We have unlocked our new home! Rotate the brass key, slide open the door, and walk inside to tour our warm housewarming invitation details.",
    primaryColor: "#d30f0f",
    extraMessage: "P.S. Home tours and warm buffet start at 1:00 PM.",
    rsvpEmail: "sharmas@wisher.net"
  },
  'blueprint-to-brick': {
    templateType: 'blueprint-to-brick',
    title: "Blueprint morphing ceremony",
    targetName: "The Reddy Family",
    date: new Date(Date.now() + 86400000 * 12).toISOString().slice(0, 16),
    message: "From drafting lines to structural bricks, we built our dream home. Click 'Build' to watch the isometric walls raise and read our invite details!",
    primaryColor: "#00ffff",
    extraMessage: "Venue address and navigation code: Sector 4B, Grid 10.",
    rsvpEmail: "reddy@wisher.net"
  },
  'isometric-neighborhood': {
    templateType: 'isometric-neighborhood',
    title: "Golden Key Neighborhood",
    targetName: "The Bhatia Family",
    date: new Date(Date.now() + 86400000 * 15).toISOString().slice(0, 16),
    message: "A new key has unlocked a house in the block! Tap the floating gold key to drop it down our chimney, slide open the roof, and see our invite details card.",
    primaryColor: "#ffd700",
    extraMessage: "Dinner and block party games. Lawn access behind house.",
    rsvpEmail: "bhatia@wisher.net"
  },
  'cozy-mailbox-reveal': {
    templateType: 'cozy-mailbox-reveal',
    title: "Letter in Mailbox",
    targetName: "The Gupta Family",
    date: new Date(Date.now() + 86400000 * 8).toISOString().slice(0, 16),
    message: "Check the mail! Pull down the red curbside flag, slide out our customized envelope, and seal open our cozy housewarming card.",
    primaryColor: "#b80c0c",
    extraMessage: "Autumn backyard fire pit and barbecue starts at 6:00 PM.",
    rsvpEmail: "guptas@wisher.net"
  },
  'cap-toss': {
    templateType: 'cap-toss',
    title: "Class of 2026 Celebration",
    targetName: "Michael Chang",
    date: new Date(Date.now() + 86400000 * 10).toISOString().slice(0, 16),
    message: "We did it! Join us to celebrate this major graduation achievement. Toss your cap, share some laughs, and let's toast to the next big adventure!",
    primaryColor: "#102a43",
    extraMessage: "Commencement afterparty starts at 7:00 PM. Dinner & drinks provided.",
    rsvpEmail: "graduate@wishes.net"
  },
  'stork-delivery': {
    templateType: 'stork-delivery',
    title: "Baby Shower Party!",
    targetName: "Baby Boy Thompson",
    date: new Date(Date.now() + 86400000 * 14).toISOString().slice(0, 16),
    message: "A tiny miracle is on the way! We invite you to share in our anticipation and joy at our upcoming baby shower.",
    primaryColor: "#f5a18a",
    extraMessage: "Guacamole & baby punch served in the garden starting at 2:00 PM.",
    rsvpEmail: "babyshower@wishes.net"
  },
  'silk-ribbon-envelope': {
    templateType: 'silk-ribbon-envelope',
    title: "The Ribbon Knot Invitation",
    targetName: "Diana & Charles",
    date: new Date(Date.now() + 86400000 * 35).toISOString().slice(0, 16),
    message: "With joyful hearts, we request the honor of your presence to celebrate our marriage. Untie our silk ribbon envelope to discover the details.",
    primaryColor: "#b89df5",
    extraMessage: "Reception and banquet waltz to follow the ceremony.",
    rsvpEmail: "royalmarriage@wishes.net",
    brideName: "Diana Spencer",
    groomName: "Charles Windsor",
    weddingTime: "11:00",
    venueName: "St Paul's Cathedral",
    googleMapsUrl: "https://maps.google.com"
  },
  'golden-keycard': {
    templateType: 'golden-keycard',
    title: "Access Granted: Welcome!",
    targetName: "The Jenkins Family",
    date: new Date(Date.now() + 86400000 * 18).toISOString().slice(0, 16),
    message: "We have unlocked our new home and can't wait to show you around! Insert the golden keycard to activate the system and view details.",
    primaryColor: "#2d6a4f",
    extraMessage: "Rooftop barbecue & house tours start at 3:00 PM.",
    rsvpEmail: "welcome@wishes.net"
  },
  'cosmic-galaxy-portal': {
    templateType: 'cosmic-galaxy-portal',
    title: "Stellar Alignment Day!",
    targetName: "Commander Shepherd",
    date: new Date(Date.now() + 86400000 * 4).toISOString().slice(0, 16),
    message: "Your special birthday is a focal alignment event in the Milky Way! Tap the singularity core to decrypt your cosmic birthday greeting scroll.",
    primaryColor: "#b89df5",
    extraMessage: "Normandy surprise party starts at 2000 hours. Dress code: N7.",
    rsvpEmail: "shepherd@citadel.net"
  },
  'diploma-roll-unwrap': {
    templateType: 'diploma-roll-unwrap',
    title: "Academic Honors Day",
    targetName: "Avery Jenkins",
    date: new Date(Date.now() + 86400000 * 15).toISOString().slice(0, 16),
    message: "Summa cum laude graduation honors have been officially rolled out! Click to unroll the leather diploma scroll and view the commencement ceremony details.",
    primaryColor: "#d4af37",
    extraMessage: "Commencement afterparty starts at 7:00 PM. Dinner & drinks provided.",
    rsvpEmail: "avery@wishes.net"
  },
  'curtain-spotlight': {
    templateType: 'curtain-spotlight',
    title: "Commencement Spotlight",
    targetName: "Michael Chang",
    date: new Date(Date.now() + 86400000 * 10).toISOString().slice(0, 16),
    message: "The stage is set! Pull the curtain cord to unveil Michael's graduation honors and celebrate this milestone achievement.",
    primaryColor: "#102a43",
    extraMessage: "Commencement afterparty starts at 7:00 PM. Dinner & drinks provided.",
    rsvpEmail: "graduate@wishes.net"
  },
  'nursery-mobile': {
    templateType: 'nursery-mobile',
    title: "Nursery Sky Mobile",
    targetName: "Baby Boy Thompson",
    date: new Date(Date.now() + 86400000 * 14).toISOString().slice(0, 16),
    message: "A new star is born! Tap the nursery mobile to spin the clouds and unlock our baby shower celebration details.",
    primaryColor: "#f5a18a",
    extraMessage: "Guacamole & baby punch served in the garden starting at 2:00 PM.",
    rsvpEmail: "babyshower@wishes.net"
  },
  'garden-gate': {
    templateType: 'garden-gate',
    title: "A Secret Garden",
    targetName: "Diana & Charles",
    date: new Date(Date.now() + 86400000 * 35).toISOString().slice(0, 16),
    message: "Open the gates to our secret garden! Tap the golden lock to swing the roses wide and reveal the details of our union.",
    primaryColor: "#b89df5",
    extraMessage: "Reception and banquet waltz to follow the ceremony.",
    rsvpEmail: "royalmarriage@wishes.net",
    brideName: "Diana Spencer",
    groomName: "Charles Windsor",
    weddingTime: "11:00",
    venueName: "St Paul's Cathedral",
    googleMapsUrl: "https://maps.google.com"
  },
  'ring-doorbell': {
    templateType: 'ring-doorbell',
    title: "Ring Our Bell!",
    targetName: "The Sharma Family",
    date: new Date(Date.now() + 86400000 * 8).toISOString().slice(0, 16),
    message: "Welcome to our new home! Ring the front porch bell to turn on the lights, open the doors, and join our housewarming party.",
    primaryColor: "#2d6a4f",
    extraMessage: "Dinner and drinks will be served. Address details are linked below.",
    rsvpEmail: "home@wisher.net"
  }
};
